name: flutter_temporary
description: "A new Flutter project."

publish_to: 'none' # This prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0  # Updated to match firebase_auth version
  firebase_auth: ^6.0.1  # Authentication version compatible with firebase_core ^3.13.0
  firebase_storage: ^13.0.0  # Updated to a compatible version with firebase_core ^3.13.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5 # For opening Google Maps or external links
  http: ^1.5.0 # For making API requests to OpenWeatherMap

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
