// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj7bhj_C4ppypmYWIoRkyXrXcpE4PHWgk',
    appId: '1:197840582255:web:afd9a236d0b5367969ff9a',
    messagingSenderId: '197840582255',
    projectId: 'travell-planner-c437e',
    authDomain: 'travell-planner-c437e.firebaseapp.com',
    storageBucket: 'travell-planner-c437e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Vx-MHQaUX3SyjAFrnaEaWwbsbQ2RIBI',
    appId: '1:197840582255:android:6d8c3de990153cfd69ff9a',
    messagingSenderId: '197840582255',
    projectId: 'travell-planner-c437e',
    storageBucket: 'travell-planner-c437e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR-Ma-IA4dhYoQ7RiUcYYJtdwZhxe5XK8',
    appId: '1:197840582255:ios:f4a89f4da14a907d69ff9a',
    messagingSenderId: '197840582255',
    projectId: 'travell-planner-c437e',
    storageBucket: 'travell-planner-c437e.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemporary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR-Ma-IA4dhYoQ7RiUcYYJtdwZhxe5XK8',
    appId: '1:197840582255:ios:f4a89f4da14a907d69ff9a',
    messagingSenderId: '197840582255',
    projectId: 'travell-planner-c437e',
    storageBucket: 'travell-planner-c437e.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemporary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj7bhj_C4ppypmYWIoRkyXrXcpE4PHWgk',
    appId: '1:197840582255:web:388c67753e08f85269ff9a',
    messagingSenderId: '197840582255',
    projectId: 'travell-planner-c437e',
    authDomain: 'travell-planner-c437e.firebaseapp.com',
    storageBucket: 'travell-planner-c437e.firebasestorage.app',
  );
}
